apiVersion: draas.primaryio.com/v1alpha1
kind: Site
metadata:
  labels:
    app.kubernetes.io/name: site
    app.kubernetes.io/instance: site-sample
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-operator
    # app.kubernetes.io/tenant: <tenant-name>
  name: site-sample
spec:
  isPrimarySite: true
  # We can skip sending info of peer site at the time of site creation. peerSite will be part of PATCH call
  peerSite: ""
  vCenter:
    ip: 10.20.3.11
    username: Administrator@primaryio.cloud
    password: PrimaryIO@123
  # vmList will be used to send list of VMs to power it ON/OFF. Not needed at the time of Site creation. vmList will be part of PATCH call
  vmList:
  - uuid: "422a9256-253f-77fd-d963-9009c4efbb7c"
    isPowerOn: false
  storagePolicySpec:
    host: "10.21.1.9"
    port: "7100"
    secret: "test"
    enckey: "enckey"
    user: "test"
