apiVersion: draas.primaryio.com/v1alpha1
kind: AppDRUnit
metadata:
  labels:
    app.kubernetes.io/name: appdrunit
    app.kubernetes.io/instance: appdrunit-sample
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-operator
  name: appdrunit-sample
spec:
  # TODO(user): Add fields here
   vCenter:
    VmUuid:
    PolicyName:
    VcHostIp: 10.20.3.11
    VcUsername: Administrator@primaryio.cloud
    VcPassword: PrimaryIO@123
