apiVersion: draas.primaryio.com/v1alpha1
kind: AppDRUnit
metadata:
  labels:
    app.kubernetes.io/name: appdrunit
    app.kubernetes.io/instance: appdrunit-sample
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-operator
  name: rk-appdrunit-sample
spec:
  site: "site-sample"
  peerSite: "site-dr-sample"
  vesToken: "vaultItem.46594.NGnnmWULCuqybPiYaNiJeenP9IVuedNCBQzcLsD0Vl2d"
  vCenter:
    ip: 10.20.3.11
    username: Administrator@primaryio.cloud
    password: PrimaryIO@123
  protectvmuuidList:
  - vmUuid: "422ab5d2-c9ff-01ab-6d66-37eaffdf99bf"
    isPolicyAttach: true
