//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/rbac/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppDRUnit) DeepCopyInto(out *AppDRUnit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppDRUnit.
func (in *AppDRUnit) DeepCopy() *AppDRUnit {
	if in == nil {
		return nil
	}
	out := new(AppDRUnit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppDRUnit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppDRUnitList) DeepCopyInto(out *AppDRUnitList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppDRUnit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppDRUnitList.
func (in *AppDRUnitList) DeepCopy() *AppDRUnitList {
	if in == nil {
		return nil
	}
	out := new(AppDRUnitList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppDRUnitList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppDRUnitSpec) DeepCopyInto(out *AppDRUnitSpec) {
	*out = *in
	if in.ProtectVMUUIDList != nil {
		in, out := &in.ProtectVMUUIDList, &out.ProtectVMUUIDList
		*out = make([]VmPolicyRequest, len(*in))
		copy(*out, *in)
	}
	out.VCenter = in.VCenter
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppDRUnitSpec.
func (in *AppDRUnitSpec) DeepCopy() *AppDRUnitSpec {
	if in == nil {
		return nil
	}
	out := new(AppDRUnitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppDRUnitStatus) DeepCopyInto(out *AppDRUnitStatus) {
	*out = *in
	if in.ProtectedVmList != nil {
		in, out := &in.ProtectedVmList, &out.ProtectedVmList
		*out = make([]VMStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FailoverVmdkListStatus != nil {
		in, out := &in.FailoverVmdkListStatus, &out.FailoverVmdkListStatus
		*out = make([]TriggerFailoverVmdkMapping, len(*in))
		copy(*out, *in)
	}
	out.FailoverStatus = in.FailoverStatus
	out.FailbackStatus = in.FailbackStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppDRUnitStatus.
func (in *AppDRUnitStatus) DeepCopy() *AppDRUnitStatus {
	if in == nil {
		return nil
	}
	out := new(AppDRUnitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Disk) DeepCopyInto(out *Disk) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Disk.
func (in *Disk) DeepCopy() *Disk {
	if in == nil {
		return nil
	}
	out := new(Disk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorField) DeepCopyInto(out *ErrorField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorField.
func (in *ErrorField) DeepCopy() *ErrorField {
	if in == nil {
		return nil
	}
	out := new(ErrorField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverResponse) DeepCopyInto(out *FailoverResponse) {
	*out = *in
	out.Data = in.Data
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverResponse.
func (in *FailoverResponse) DeepCopy() *FailoverResponse {
	if in == nil {
		return nil
	}
	out := new(FailoverResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverStatus) DeepCopyInto(out *FailoverStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverStatus.
func (in *FailoverStatus) DeepCopy() *FailoverStatus {
	if in == nil {
		return nil
	}
	out := new(FailoverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IsPolicyExistsSchema) DeepCopyInto(out *IsPolicyExistsSchema) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IsPolicyExistsSchema.
func (in *IsPolicyExistsSchema) DeepCopy() *IsPolicyExistsSchema {
	if in == nil {
		return nil
	}
	out := new(IsPolicyExistsSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyDetails) DeepCopyInto(out *PolicyDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyDetails.
func (in *PolicyDetails) DeepCopy() *PolicyDetails {
	if in == nil {
		return nil
	}
	out := new(PolicyDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Site) DeepCopyInto(out *Site) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Site.
func (in *Site) DeepCopy() *Site {
	if in == nil {
		return nil
	}
	out := new(Site)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Site) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteList) DeepCopyInto(out *SiteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Site, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteList.
func (in *SiteList) DeepCopy() *SiteList {
	if in == nil {
		return nil
	}
	out := new(SiteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteSpec) DeepCopyInto(out *SiteSpec) {
	*out = *in
	if in.SiteAdmins != nil {
		in, out := &in.SiteAdmins, &out.SiteAdmins
		*out = make([]v1.Subject, len(*in))
		copy(*out, *in)
	}
	out.VCenter = in.VCenter
	if in.VMList != nil {
		in, out := &in.VMList, &out.VMList
		*out = make([]VMSpec, len(*in))
		copy(*out, *in)
	}
	out.StoragePolicy = in.StoragePolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteSpec.
func (in *SiteSpec) DeepCopy() *SiteSpec {
	if in == nil {
		return nil
	}
	out := new(SiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteStatus) DeepCopyInto(out *SiteStatus) {
	*out = *in
	if in.VmList != nil {
		in, out := &in.VmList, &out.VmList
		*out = make([]VMStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Error = in.Error
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteStatus.
func (in *SiteStatus) DeepCopy() *SiteStatus {
	if in == nil {
		return nil
	}
	out := new(SiteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePolicySpec) DeepCopyInto(out *StoragePolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePolicySpec.
func (in *StoragePolicySpec) DeepCopy() *StoragePolicySpec {
	if in == nil {
		return nil
	}
	out := new(StoragePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerFailoverVmdkMapping) DeepCopyInto(out *TriggerFailoverVmdkMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerFailoverVmdkMapping.
func (in *TriggerFailoverVmdkMapping) DeepCopy() *TriggerFailoverVmdkMapping {
	if in == nil {
		return nil
	}
	out := new(TriggerFailoverVmdkMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCenterSpec) DeepCopyInto(out *VCenterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCenterSpec.
func (in *VCenterSpec) DeepCopy() *VCenterSpec {
	if in == nil {
		return nil
	}
	out := new(VCenterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMDKFromPostGresDResponse) DeepCopyInto(out *VMDKFromPostGresDResponse) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMDKFromPostGresDResponse.
func (in *VMDKFromPostGresDResponse) DeepCopy() *VMDKFromPostGresDResponse {
	if in == nil {
		return nil
	}
	out := new(VMDKFromPostGresDResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMDKListFromPostGresDResponse) DeepCopyInto(out *VMDKListFromPostGresDResponse) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]VMDKFromPostGresDResponse, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMDKListFromPostGresDResponse.
func (in *VMDKListFromPostGresDResponse) DeepCopy() *VMDKListFromPostGresDResponse {
	if in == nil {
		return nil
	}
	out := new(VMDKListFromPostGresDResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMSpec) DeepCopyInto(out *VMSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMSpec.
func (in *VMSpec) DeepCopy() *VMSpec {
	if in == nil {
		return nil
	}
	out := new(VMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMStatus) DeepCopyInto(out *VMStatus) {
	*out = *in
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]Disk, len(*in))
		copy(*out, *in)
	}
	if in.IpAddress != nil {
		in, out := &in.IpAddress, &out.IpAddress
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMStatus.
func (in *VMStatus) DeepCopy() *VMStatus {
	if in == nil {
		return nil
	}
	out := new(VMStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmPolicyRequest) DeepCopyInto(out *VmPolicyRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmPolicyRequest.
func (in *VmPolicyRequest) DeepCopy() *VmPolicyRequest {
	if in == nil {
		return nil
	}
	out := new(VmPolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmPolicySchema) DeepCopyInto(out *VmPolicySchema) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmPolicySchema.
func (in *VmPolicySchema) DeepCopy() *VmPolicySchema {
	if in == nil {
		return nil
	}
	out := new(VmPolicySchema)
	in.DeepCopyInto(out)
	return out
}
